### ISSUE TITLE
Mudar nomenclatura do arquivo de instruções

### ISSUE THREAD

**Issue by tiagopapile** [flaubert-dev/docker-wordpress-padronizado#1]
@Dev-Flaubert-Wordpress Parabéns pela iniciativa :)

Deixo só a sugestão de mudar o arquivo `LEIA-ME.txt` para `README.md`, assim fica padronizado e melhora a leitura no Github.

**Comment by flaubert-dev** [comment]
> @Dev-Flaubert-Wordpress Parabéns pela iniciativa :)
> 
> Deixo só a sugestão de mudar o arquivo `LEIA-ME.txt` para `README.md`, assim fica padronizado e melhora a leitura no Github.

Gratidão meu bom!! :D
Pode deixar, mudo sim para o `README.md` em breve :)

**Comment by flaubert-dev** [comment]
> @Dev-Flaubert-Wordpress Parabéns pela iniciativa :)
> 
> Deixo só a sugestão de mudar o arquivo `LEIA-ME.txt` para `README.md`, assim fica padronizado e melhora a leitura no Github.

Agora sim meu bom, README.txt concluído 👍 
Qualquer sugestão / melhoria é só me avisar @tiagopapile :)
